name: Quality

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["PR build"]
    types:
      - completed

jobs:
  quality:
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
      issues: write
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: coverage
        uses: 5monkeys/cobertura-action@master
        with:
            path: coverage/coverage_xml.xml
            minimum_coverage: 75
            show_line: true
            show_branch: true
